"""asd

Revision ID: 002e9e71dab6
Revises: ff69eb86c676
Create Date: 2025-06-16 11:34:02.924921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002e9e71dab6'
down_revision = 'ff69eb86c676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_administrator_table', schema=None) as batch_op:
        batch_op.alter_column('is_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_administrator_table', schema=None) as batch_op:
        batch_op.alter_column('is_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
