"""added payment

Revision ID: 145ddf89bc28
Revises: bb7f669edbc3
Create Date: 2025-06-19 07:52:15.949858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145ddf89bc28'
down_revision = 'bb7f669edbc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrance_fee_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues_table', schema=None) as batch_op:
        batch_op.drop_column('entrance_fee_amount')

    # ### end Alembic commands ###
