"""on delete

Revision ID: 2a371663efc4
Revises: 4cafe8a1a78e
Create Date: 2025-06-20 09:16:06.077315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a371663efc4'
down_revision = '4cafe8a1a78e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint('teams_table_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users_table', ['user_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teams_table_user_id_fkey', 'users_table', ['user_id'], ['user_id'])
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
