"""fix my_teams

Revision ID: 54787661ea05
Revises: 9157016ffae1
Create Date: 2025-06-10 20:44:53.180118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54787661ea05'
down_revision = '9157016ffae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players_table', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players_table', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
