"""added is req

Revision ID: 54c797f27537
Revises: 2a371663efc4
Create Date: 2025-06-22 15:50:24.619057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c797f27537'
down_revision = '2a371663efc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recruiting', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.drop_column('is_recruiting')

    # ### end Alembic commands ###
