"""add on delete

Revision ID: 5f6bb40b1ba6
Revises: acfb316097bf
Create Date: 2025-06-14 10:51:09.702088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6bb40b1ba6'
down_revision = 'acfb316097bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_categories_table', schema=None) as batch_op:
        batch_op.drop_constraint('league_categories_table_league_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'leagues_table', ['league_id'], ['league_id'], ondelete='CASCADE')

    with op.batch_alter_table('leagues_table', schema=None) as batch_op:
        batch_op.alter_column('league_administrator_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint('leagues_table_league_administrator_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'league_administrator_table', ['league_administrator_id'], ['league_administrator_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('leagues_table_league_administrator_id_fkey', 'league_administrator_table', ['league_administrator_id'], ['league_administrator_id'])
        batch_op.alter_column('league_administrator_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('league_categories_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('league_categories_table_league_id_fkey', 'leagues_table', ['league_id'], ['league_id'])

    # ### end Alembic commands ###
