"""1

Revision ID: 6c1ae6b14e61
Revises: 
Create Date: 2025-06-10 16:59:15.662398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1ae6b14e61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('jersey_name', sa.String(length=1000), nullable=False))
        batch_op.add_column(sa.Column('jersey_number', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('position', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('height_in', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('games_played', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('points_scored', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('assists', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rebounds', sa.Integer(), nullable=False))
        batch_op.drop_constraint('players_table_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users_table', ['user_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('players_table_user_id_fkey', 'users_table', ['user_id'], ['user_id'])
        batch_op.drop_column('rebounds')
        batch_op.drop_column('assists')
        batch_op.drop_column('points_scored')
        batch_op.drop_column('games_played')
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('height_in')
        batch_op.drop_column('position')
        batch_op.drop_column('jersey_number')
        batch_op.drop_column('jersey_name')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('gender')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
