"""address

Revision ID: 6d4bb50ef79c
Revises: c67e233b8aaf
Create Date: 2025-06-18 20:20:49.957960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4bb50ef79c'
down_revision = 'c67e233b8aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_address', sa.String(length=250), nullable=False))
        batch_op.drop_column('barangay_name')
        batch_op.drop_column('municipality_name')

    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.alter_column('team_address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.alter_column('team_address',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('players_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('municipality_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('barangay_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('player_address')

    # ### end Alembic commands ###
