"""later coach

Revision ID: 6eb4ef89723f
Revises: ef5e091c27bb
Create Date: 2025-06-15 10:04:32.900469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb4ef89723f'
down_revision = 'ef5e091c27bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.drop_constraint('teams_table_team_captain_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'player_team_table', ['team_captain_id'], ['player_team_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teams_table_team_captain_id_fkey', 'players_table', ['team_captain_id'], ['player_id'])

    # ### end Alembic commands ###
