"""added  team logo

Revision ID: 86305485918f
Revises: 5f6bb40b1ba6
Create Date: 2025-06-14 23:05:01.345916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86305485918f'
down_revision = '5f6bb40b1ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_logo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.drop_column('team_logo')

    # ### end Alembic commands ###
