"""added image urls in player

Revision ID: 9157016ffae1
Revises: 6c1ae6b14e61
Create Date: 2025-06-10 20:38:45.663216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9157016ffae1'
down_revision = '6c1ae6b14e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=1000), nullable=False))
        batch_op.add_column(sa.Column('document_url_1', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('document_url_2', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players_table', schema=None) as batch_op:
        batch_op.drop_column('document_url_2')
        batch_op.drop_column('document_url_1')
        batch_op.drop_column('profile_image_url')

    # ### end Alembic commands ###
