"""asdasd

Revision ID: 99e0e2ea249a
Revises: 
Create Date: 2025-06-16 16:26:35.212296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e0e2ea249a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ban', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_allowed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_team_captain_id', 'player_team_table', ['team_captain_id'], ['player_team_id'], deferrable=True, use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_team_captain_id', type_='foreignkey')

    with op.batch_alter_table('players_table', schema=None) as batch_op:
        batch_op.drop_column('is_allowed')
        batch_op.drop_column('is_ban')

    # ### end Alembic commands ###
