"""init

Revision ID: acfb316097bf
Revises: 
Create Date: 2025-06-14 10:29:33.655890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acfb316097bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_administrator_table', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users_table', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('league_categories_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_format', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('stage', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('max_team', sa.Integer(), nullable=False))

    with op.batch_alter_table('leagues_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('opening_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('banner_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('league_rules', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('sponsors', sa.Text(), nullable=True))
        batch_op.alter_column('league_description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('league_budget',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('league_picture_url')
        batch_op.drop_column('league_name')

    with op.batch_alter_table('player_team_table', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'players_table', ['player_id'], ['player_id'])

    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users_table', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('player_team_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('leagues_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('league_picture_url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.alter_column('league_budget',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('league_description',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('sponsors')
        batch_op.drop_column('league_rules')
        batch_op.drop_column('status')
        batch_op.drop_column('banner_url')
        batch_op.drop_column('start_date')
        batch_op.drop_column('opening_date')
        batch_op.drop_column('league_title')

    with op.batch_alter_table('league_categories_table', schema=None) as batch_op:
        batch_op.drop_column('max_team')
        batch_op.drop_column('stage')
        batch_op.drop_column('category_format')

    with op.batch_alter_table('league_administrator_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
