"""change to address

Revision ID: bb7f669edbc3
Revises: bd26a331081c
Create Date: 2025-06-18 20:47:33.148725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7f669edbc3'
down_revision = 'bd26a331081c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_administrator_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_operational', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('organization_address', sa.String(length=250), nullable=False))
        batch_op.drop_column('municipality_name')
        batch_op.drop_column('barangay_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_administrator_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barangay_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('municipality_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('organization_address')
        batch_op.drop_column('is_operational')

    # ### end Alembic commands ###
