"""changes somthing in team

Revision ID: ef5e091c27bb
Revises: 86305485918f
Create Date: 2025-06-15 09:56:08.294164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5e091c27bb'
down_revision = '86305485918f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_league_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('barangay_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('municipality_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('team_motto', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('team_logo_url', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('assistant_coach_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('total_wins', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_losses', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('team_captain_id', sa.String(), nullable=True))
        batch_op.alter_column('championships_won',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('coach_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_foreign_key(None, 'players_table', ['team_captain_id'], ['player_id'])
        batch_op.create_foreign_key(None, 'leagues_table', ['active_league_id'], ['league_id'])
        batch_op.drop_column('team_address')
        batch_op.drop_column('team_logo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_logo', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('team_address', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('coach_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('championships_won',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('team_captain_id')
        batch_op.drop_column('total_losses')
        batch_op.drop_column('total_wins')
        batch_op.drop_column('assistant_coach_name')
        batch_op.drop_column('team_logo_url')
        batch_op.drop_column('team_motto')
        batch_op.drop_column('municipality_name')
        batch_op.drop_column('barangay_name')
        batch_op.drop_column('active_league_id')

    # ### end Alembic commands ###
