"""init

Revision ID: ff69eb86c676
Revises: 
Create Date: 2025-06-16 11:29:03.200127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff69eb86c676'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_administrator_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_allowed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_administrator_table', schema=None) as batch_op:
        batch_op.drop_column('is_allowed')

    # ### end Alembic commands ###
